//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMedicos
    {
        public int Idmedico { get; set; }
        public string CedulaProfesional { get; set; }
        public string CedulaEspecialidad { get; set; }
        public string CertCMCP { get; set; }
        public string RFC { get; set; }
        public Nullable<byte> PediatraPlus { get; set; }
        public string NoRegSSA { get; set; }
        public string DomicilioConsultorio { get; set; }
        public string TelefonoConsultorio { get; set; }
        public string TelefonoFax { get; set; }
        public string codigopostal { get; set; }
        public string NoExt { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Domicilio { get; set; }
        public string Colonia { get; set; }
        public string Telefono { get; set; }
        public string TelefonoCel { get; set; }
        public string Emails { get; set; }
        public Nullable<System.DateTime> FechaRenovacion { get; set; }
        public string ciudad { get; set; }
        public string especialidad { get; set; }
        public string Estado { get; set; }
        public string idEstado { get; set; }
        public string IdPais { get; set; }
        public Nullable<int> idciudad { get; set; }
    }
}
