
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DosisAplicadaVacuna
{

    public int IdDosis { get; set; }

    public string Dosis { get; set; }

    public string Edad { get; set; }

    public Nullable<System.DateTime> FechaVacunacion { get; set; }

    public int IdVacuna { get; set; }

}

}
