
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Estudios
{

    public int idEstudio { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string NombreEstudio { get; set; }

    public string CentroMedico { get; set; }

    public Nullable<int> idexpediente { get; set; }

    public string Resultado { get; set; }

}

}
