
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Familiares
{

    public string Nombre { get; set; }

    public string Sexo { get; set; }

    public int IdFamiliar { get; set; }

    public Nullable<System.DateTime> Nacimiento { get; set; }

    public string Enfermedades { get; set; }

    public int Relacion { get; set; }

    public string DetalleRelacion { get; set; }

    public Nullable<int> idpaciente { get; set; }

}

}
