
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Imagenes
{

    public int IdImagen { get; set; }

    public Nullable<int> idExpediente { get; set; }

    public string Archivo { get; set; }

    public string ArchivoThumb { get; set; }

}

}
