

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class emeciEntities : DbContext
{
    public emeciEntities()
        : base("name=emeciEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CatCategoEstudios> CatCategoEstudios { get; set; }

    public virtual DbSet<catdiagnostico> catdiagnostico { get; set; }

    public virtual DbSet<CatEstudios> CatEstudios { get; set; }

    public virtual DbSet<catrecetas> catrecetas { get; set; }

    public virtual DbSet<ConsultaGinecologa> ConsultaGinecologa { get; set; }

    public virtual DbSet<ConsultaObstetrica> ConsultaObstetrica { get; set; }

    public virtual DbSet<Consultas> Consultas { get; set; }

    public virtual DbSet<DatosTarjeta> DatosTarjeta { get; set; }

    public virtual DbSet<Diagnosticos> Diagnosticos { get; set; }

    public virtual DbSet<DiagnosticosExc> DiagnosticosExc { get; set; }

    public virtual DbSet<Especialidades> Especialidades { get; set; }

    public virtual DbSet<EstudiosGab> EstudiosGab { get; set; }

    public virtual DbSet<EstudiosLab> EstudiosLab { get; set; }

    public virtual DbSet<Familiares> Familiares { get; set; }

    public virtual DbSet<Patologias> Patologias { get; set; }

    public virtual DbSet<Recetas> Recetas { get; set; }

    public virtual DbSet<Registro> Registro { get; set; }

    public virtual DbSet<Vacunas> Vacunas { get; set; }

    public virtual DbSet<Estados> Estados { get; set; }

    public virtual DbSet<Estudios> Estudios { get; set; }

    public virtual DbSet<Imagenes> Imagenes { get; set; }

    public virtual DbSet<Medico> Medico { get; set; }

    public virtual DbSet<Tarjetas> Tarjetas { get; set; }

    public virtual DbSet<TemaComentarios> TemaComentarios { get; set; }

    public virtual DbSet<Temas> Temas { get; set; }

    public virtual DbSet<trackermedicos> trackermedicos { get; set; }

    public virtual DbSet<Ciudades> Ciudades { get; set; }

    public virtual DbSet<Paciente> Paciente { get; set; }

    public virtual DbSet<DosisAplicadaVacuna> DosisAplicadaVacuna { get; set; }

    public virtual DbSet<ListaVacunas> ListaVacunas { get; set; }

}

}

