
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tarjetas
{

    public string idtarjeta { get; set; }

    public string NoTarjeta { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }

    public Nullable<System.DateTime> FechaExpira { get; set; }

    public Nullable<byte> EjeX { get; set; }

    public Nullable<byte> EjeY { get; set; }

}

}
