
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TemaComentarios
{

    public Nullable<int> IdTemaComentario { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> IdMedico { get; set; }

    public string Comentario { get; set; }

    public Nullable<byte> Status { get; set; }

    public int idtema { get; set; }

}

}
