
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Temas
{

    public int IdTema { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> idMedicoCreo { get; set; }

}

}
