
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmeciExpediente.Models
{

using System;
    using System.Collections.Generic;
    
public partial class trackermedicos
{

    public int idtracker { get; set; }

    public string TypeLink { get; set; }

    public Nullable<int> idmedico { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

}

}
